apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-new-project-deployment   # deployment name
spec:
  replicas: 2                        # number of pods
  selector:
    matchLabels:
      app: my-new-project
  template:
    metadata:
      labels:
        app: my-new-project
    spec:
      containers:
        - name: my-new-project
          image: 228948463033.dkr.ecr.us-east-1.amazonaws.com/newone:latest
          ports:
            - containerPort: 3000
