apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_new_project-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my_new_project
  template:
    metadata:
      labels:
        app: my_new_project
    spec:
      containers:
        - name: my_new_project
          image: 228948463033.dkr.ecr.us-east-1.amazonaws.com/newone:latest
          ports:
            - containerPort: 5000
