apiVersion: v1
kind: Service
metadata:
  name: my-new-project-service
spec:
  type: LoadBalancer
  selector:
    app: my-new-project            # must match deployment labels
  ports:
    - port: 80                     # public port
      targetPort: 3000             # container port
