apiVersion: v1
kind: Service
metadata:
  name: my-new-project-service
spec:
  type: LoadBalancer
  selector:
    app: my-new-project
  ports:
    - protocol: TCP
      port: 80          # Public port
      targetPort: 5000  # Container port
